-- MySQL Script generated by MySQL Workbench
-- Mon May 28 11:50:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotelsite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelsite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelsite` DEFAULT CHARACTER SET utf8 ;
USE `hotelsite` ;

-- -----------------------------------------------------
-- Table `hotelsite`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`users` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `country` VARCHAR(30) NULL,
  `manager` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelsite`.`hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`hotels` (
  `hotelid` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `hotelname` VARCHAR(45) NOT NULL,
  `hoteldescription` VARCHAR(300) NULL,
  `extendeddescription` VARCHAR(350) NULL,
  `cost` INT NULL,
  `additionalinfo` VARCHAR(45) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `userrating` INT NULL,
  `hotelrating` INT NULL,
  PRIMARY KEY (`hotelid`),
  UNIQUE INDEX `hotelid_UNIQUE` (`hotelid` ASC),
  INDEX `userid_idx` (`userid` ASC),
  CONSTRAINT `hotelsuserid`
    FOREIGN KEY (`userid`)
    REFERENCES `hotelsite`.`users` (`userid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelsite`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`reviews` (
  `reviewid` INT NOT NULL AUTO_INCREMENT,
  `hotelid` INT NULL,
  `userid` INT NULL,
  `dateposted` DATE NULL,
  `reviewtext` VARCHAR(300) NULL,
  `likes` INT NULL,
  `dislikes` INT NULL,
  `rating` INT NULL,
  PRIMARY KEY (`reviewid`),
  INDEX `userid_idx` (`userid` ASC),
  INDEX `hotelid_idx` (`hotelid` ASC),
  CONSTRAINT `reviewsuserid`
    FOREIGN KEY (`userid`)
    REFERENCES `hotelsite`.`users` (`userid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `reviewshotelid`
    FOREIGN KEY (`hotelid`)
    REFERENCES `hotelsite`.`hotels` (`hotelid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelsite`.`hotelfilters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`hotelfilters` (
  `hotelid` INT NOT NULL,
  `kingbed` TINYINT NULL DEFAULT 0,
  `queenbed` TINYINT NULL DEFAULT 0,
  `singlebed` TINYINT NULL DEFAULT 0,
  `breakfast` TINYINT NULL DEFAULT 0,
  `freewifi` TINYINT NULL DEFAULT 0,
  `pool` TINYINT NULL DEFAULT 0,
  INDEX `hotelid_idx` (`hotelid` ASC),
  CONSTRAINT `filtershotelid`
    FOREIGN KEY (`hotelid`)
    REFERENCES `hotelsite`.`hotels` (`hotelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelsite`.`deals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`deals` (
  `hotelid` INT NOT NULL,
  `info` VARCHAR(150) NULL,
  INDEX `hotelid_idx` (`hotelid` ASC),
  CONSTRAINT `dealshotelid`
    FOREIGN KEY (`hotelid`)
    REFERENCES `hotelsite`.`hotels` (`hotelid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelsite`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`rooms` (
  `hotelid` INT NULL,
  `roomtype` VARCHAR(30) NULL,
  `roomcost` VARCHAR(30) NULL,
  INDEX `hotelid_idx` (`hotelid` ASC),
  CONSTRAINT `roomshotelid`
    FOREIGN KEY (`hotelid`)
    REFERENCES `hotelsite`.`hotels` (`hotelid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelsite`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelsite`.`bookings` (
  `bookingid` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `hotelid` INT NULL,
  `datein` DATE NULL,
  `dateout` DATE NULL,
  `roomnum` INT NULL,
  `imagefile` VARCHAR(100) NULL,
  `cost` INT NULL,
  `paymentfulfilled` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`bookingid`),
  INDEX `hotelid_idx` (`hotelid` ASC),
  INDEX `userid_idx` (`userid` ASC),
  CONSTRAINT `bookingshotelid`
    FOREIGN KEY (`hotelid`)
    REFERENCES `hotelsite`.`hotels` (`hotelid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `bookingsuserid`
    FOREIGN KEY (`userid`)
    REFERENCES `hotelsite`.`users` (`userid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
